apiVersion: v1
kind: Namespace
metadata:
  name: nginx-config-test
  labels:
    app: nginx-config-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-config-test
  namespace: nginx-config-test
  labels:
    app: nginx-config-test
    aadpodidbinding: blob-identity  # specify the selector defined in AzureIdentityBinding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-config-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginx-config-test
    spec:
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index
          items:
          - key: index
            path: index.html
      containers:
      - name: nginx
        image: nginx:1.17.9-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html/
          readOnly: true          
        resources:
          requests: # minimum resources required
            cpu: 125m
            memory: 128Mi
          limits: # maximum resources allocated
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-config-test
  namespace: nginx-config-test
  labels:
    app: nginx-config-test
spec:
  selector:
    app: nginx-config-test
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: nginx-config-test
  labels:
    app: nginx-config-test
data:
  index: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; }
    </style>
    </head>
    <body>
    <h1>Welcome to nginx!</h1>
    <p>If you see this page, the nginx web server is successfully installed and
    working. Further configuration is required.</p>

    <p>For online documentation and support please refer to
    <a href="http://nginx.org/">nginx.org</a>.<br/>
    Commercial support is available at
    <a href="http://nginx.com/">nginx.com</a>.</p>

    <p><em>Thank you for using nginx.</em></p>
    </body>
    </html>