apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blob-test
  namespace: nginx-blob-test
  labels:
    app: nginx-blob-test
    aadpodidbinding: blob-identity  # specify the selector defined in AzureIdentityBinding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-blob-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nginx-blob-test
        aadpodidbinding: blob-identity  # specify the selector defined in AzureIdentityBinding
    spec:
      volumes:
      - name: nginx-index
        emptyDir: {}            
      initContainers:
      - name: blob-loader
        image: radial/busyboxplus:curl
        command: ["/bin/sh","-c"]
        args:
        - access_token=$(curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fstorage.azure.com%2F' -H Metadata:true -s | sed -nE 's/.*"access_token":"([^\"]*)",".*/\1/p');
          curl -s 'https://<my-storage-account>.blob.core.windows.net/blob-test/index.html' -H "x-ms-version:2017-11-09" -H "Authorization:Bearer ${access_token}" > /data/index.html;
        volumeMounts:
        - name: nginx-index
          mountPath: /data          
      containers:
      - name: nginx
        image: nginx:1.17.9-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html/
          readOnly: true          
        resources:
          requests: # minimum resources required
            cpu: 125m
            memory: 128Mi
          limits: # maximum resources allocated
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-blob-test
  namespace: nginx-blob-test
  labels:
    app: nginx-blob-test
spec:
  selector:
    app: nginx-blob-test
  ports:
    - protocol: TCP
      port: 80