# Create azure identities and bindings
azureIdentities: 
  - name: "demo-identity"
    # if not defined, then the azure identity will be deployed in the same namespace as the chart
    # namespace: ""
    # type 0: MSI, type 1: Service Principal
    type: 0
    # /subscriptions/<your-subscription-id>/resourcegroups/<identity-resource-group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity-name>
    resourceID: "/subscriptions/<your-subscription-id>/resourceGroups/<identity-resource-group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity-name>"
    clientID: "1c968edd-b896-440a-82c7-cb166ba3e700"
    binding:
      name: "demo-identity-binding"
      # The selector will also need to be included in labels for app deployment
      selector: "demo"
